### ISSUE TITLE
HTTPoison 1.8 -> 2.1

### ISSUE THREAD

**Issue by BrooklinJazz** [dvcrn/ex_openai#1]
The HTTPoison version for this project is outdated.

Happy to make a PR to update the version if you are interested and if there's no specific reason to use 1.8.

**Comment by dvcrn** [comment]
Thanks for pointing this out 

good question, I don’t think there was a particular reason for 1.8

**Comment by BrooklinJazz** [comment]
In that case, I can bump up the version when I have time if you'd like. Or I'm happy to leave it alone if you'd like to do it faster than I can.

I love this library, by the way. My student started using it and shared it with me. It's fantastic! Happy to help out if you ever need a second pair of hands. I'm sure my student feels the same way.

**Comment by dvcrn** [comment]
Pull requests are always welcome ❤️ 

I can probably get to it this weekend or later at earliest, so any help is greatly appreciated. Should be a very small change anyway

**Comment by BrooklinJazz** [comment]
While there, I made a separate PR to make the Mock dependency in the test env only since I'm currently overwriting it. #3 

P.S. would love to have you on the Elixir Newbie podcast to talk about this project :D Message me anytime on Twitter https://twitter.com/BrooklinJMyers or email brooklin@elixirnewbie.com if that sounds like fun.

Either way, thank you again for making this library. Reach out anytime if I can help!

**Comment by dvcrn** [comment]
Released in 1.1.1, thanks for the PR and sorry for taking a while!

Podcast sounds interesting, I'll reach out on Twitter 😄
