### ISSUE TITLE
Jason decode errors while streaming assistants API

### ISSUE THREAD

**Issue by thiagomajesk** [dvcrn/ex_openai#23]
Hi! I'm getting the following Jason decoded errors while streaming using the assistant API. The example is pretty much the same as the [Streaming with a callback function](https://github.com/dvcrn/ex_openai?tab=readme-ov-file#streaming-with-a-callback-function) section, but using  `ExOpenAI.Threads.create_thread_and_run/2` instead.

```elixir
Error: %Jason.DecodeError{position: 491, token: nil, ...}
Error: %Jason.DecodeError{position: 0, token: nil, ...}
```

It seems that both V1 and V2 APIs are not working, while V2 is the only one that goes through and returns the errors.

**Comment by dvcrn** [comment]
Thanks for reporting! Let me try to look into this when I'm with a bit more time
